spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/notifications?ssl=false
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

app:
  email:
    enabled: true
#    default-email: "ion@thehousehealth.com"
    default-email: "no-reply@thehousehealth.com"
  portal-user-link: "https://therapist-portal-dev.thehousehealth.com/#/clients/details/"
  push:
    enabled: false

management:
  health:
    show-details: always
    probes.enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.agenatech: DEBUG

springdoc.api-docs.path: /api/v1/notification-service/api-doc

health:
  config:
    enabled: false