spring:
  datasource:
    url: jdbc:postgresql://database-prod-3.co7q08si9fnn.eu-north-1.rds.amazonaws.com:5432/health-data?ssl=false
    username: postgres
    password: '{cipher}d5017eb5d20ba018bbf4d8a517add0900009154666fce99aa970a8b0527aaa7119442deee01344fdc9ce55bca3e24c2a'
    hikari:
      connection-timeout: 20000