spring:
  cloud:
    gateway:
      routes:
        - id: profiles
          uri: http://profiles
          predicates:
            - Path=/api/v1/profiles/me
            - Method=GET,PUT,PATCH,DELETE
          filters:
            - AddPrincipalToPathFilter
        - id: openapi
          uri: http://api-gateway
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /api/v1//$\{path}/api-doc
        - id: ai-management
          uri: http://ai-management:9090
          predicates:
            - Path=/api/v1/emotions,/api/v1/sleep
            - Method=GET,POST
keycloak-client:
  server-url: https://auth-dev.agenadev.com/auth
