spring:
  cloud:
    gateway:
      routes:
        - id: profilesPrincipal
          uri: http://profiles
          predicates:
            - Path=/api/v1/profiles/me
            - Method=GET,PUT,PATCH,DELETE
          filters:
            - AddPrincipalToPathFilter
        - id: profiles
          uri: http://profiles
          predicates:
            - Path=/api/v1/profiles/*/*, /api/v1/profiles/api-doc
        - id: openapi
          uri: http://api-gateway
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /api/v1//$\{path}/api-doc
        - id: ai-management
          uri: http://ai-management:9090
          predicates:
            - Path=/api/v1/emotions/**,/api/v1/sleep,/api/v1/sleep/**,/api/v1/ai-management/api-doc
            - Method=GET,POST
        - id: gamification-manager-admin
          uri: http://gamification-manager
          predicates:
            - Path=/api/v1/cards/**, /api/v1/tasks/**
            - Method=POST,PATCH,DELETE
          metadata:
            auth-roles:
              - admin-diar
        - id: gamification-manager-therapist
          uri: http://gamification-manager
          predicates:
            - Path=/api/v1/achievements/**, /api/v1/posts/**, /api/v1/steps/**, /api/v1/therapist/**
            - Method=POST,PATCH,DELETE
          metadata:
            auth-roles:
              - admin-diar
              - therapist-diar
        - id: gamification-manager
          uri: http://gamification-manager
          predicates:
            - Path=/api/v1/achievements/**, /api/v1/cards/**, /api/v1/posts/**, /api/v1/steps/**, /api/v1/tasks/**, /api/v1/gamification-manager/**
            - Method=GET
        - id: descriptions
          uri: http://gamification-manager
          predicates:
            - Path=/api/v1/*/*/description
            - Method=GET,PUT,PATCH
          filters:
            - RewritePath=/api/v1/(?<entity>.*)/(?<path>.*)/description, /api/v1/description//$\{path}/
        - id: keycloak-admin-adapter
          uri: http://keycloak-admin-adapter
          predicates:
            - Path=/api/v1/sso/**
          filters:
            - AddPrincipalToPathFilter
          metadata:
            auth-roles:
              - admin-diar
              - therapist-diar
        - id: keycloak-admin-adapter-openAPI
          uri: http://keycloak-admin-adapter
          predicates:
            - Path=/api/v1/keycloak-admin-adapter/api-doc
        - id: multimedia
          uri: http://multimedia-manager
          predicates:
            - Path=/api/v1/multimedia, /api/v1/multimedia/**, /api/v1/multimedia-manager/**
keycloak-client:
  server-url: https://auth-dev.agenadev.com/auth
