spring:
  cloud:
    gateway:
      routes:
        - id: profiles-therapist
          uri: http://profiles
          predicates:
            - Path=/api/v1/profiles/me/set-client-step/**
            - Method=POST
          filters:
            - AddPrincipalToPathFilter
          metadata:
            auth-roles:
              - therapist-diar
        - id: profiles-principal
          uri: http://profiles
          predicates:
            - Path=/api/v1/profiles/me
            - Method=GET,PUT,PATCH,DELETE
          filters:
            - AddPrincipalToPathFilter
        - id: profiles
          uri: http://profiles
          predicates:
            - Path=/api/v1/profiles/*/*, /api/v1/profiles/api-doc
            - Method=GET
        - id: openapi
          uri: http://api-gateway
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /api/v1//$\{path}/api-doc
        - id: ai-management
          uri: http://ai-management:9090
          predicates:
            - Path=/api/v1/emotions/**,/api/v1/sleep,/api/v1/sleep/**,/api/v1/ai-management/api-doc
            - Method=GET,POST
        - id: health-data
          uri: http://health-data
          predicates:
            - Path=/api/v1/users/me/hrv, /api/v1/users/me/steps, /api/v1/health-data/api-doc
            - Method=GET,POST
          filters:
            - AddPrincipalToPathFilter
        - id: gamification-manager-principal
          uri: http://gamification-manager
          predicates:
            - Path=/api/v1/commands/client/me/**
            - Method=POST,GET
          filters:
            - AddPrincipalToPathFilter
        - id: gamification-manager-admin
          uri: http://gamification-manager
          predicates:
            - Path=/api/v1/cards/**, /api/v1/cards, /api/v1/tasks/**, /api/v1/tasks, /api/v1/categories/**, /api/v1/categories, /api/v1/task-executions/**
            - Method=POST,PATCH,DELETE,GET
          metadata:
            auth-roles:
              - admin-diar
        - id: gamification-manager-therapist
          uri: http://gamification-manager
          predicates:
            - Path=/api/v1/posts/**
            - Method=POST,PATCH,DELETE
          metadata:
            auth-roles:
              - admin-diar
              - therapist-diar
        - id: gamification-manager
          uri: http://gamification-manager
          predicates:
            - Path=/api/v1/cards/**, /api/v1/posts/**, /api/v1/tasks/**, /api/v1/categories/**, /api/v1/gamification-manager/**
            - Method=GET
        - id: descriptions
          uri: http://gamification-manager
          predicates:
            - Path=/api/v1/*/*/description
            - Method=GET,PUT,PATCH
          filters:
            - RewritePath=/api/v1/(?<entity>.*)/(?<path>.*)/description, /api/v1/description//$\{path}/
        - id: keycloak-admin-adapter
          uri: http://keycloak-admin-adapter
          predicates:
            - Path=/api/v1/sso/accounts/me, /api/v1/keycloak-admin-adapter/api-doc
            - Method=GET,DELETE
          filters:
            - AddPrincipalToPathFilter
        - id: keycloak-admin-adapter-therapist-admin
          uri: http://keycloak-admin-adapter
          predicates:
            - Path=/api/v1/sso/me/create-account-profile, /api/v1/sso/admin/accounts/**
          filters:
            - AddPrincipalToPathFilter
          metadata:
            auth-roles:
              - admin-diar
              - therapist-diar
        - id: achievements-admin
          uri: http://achievements-manager
          predicates:
            - Path=/api/v1/achievements/**, /api/v1/achievements-monthly/**, /api/v1/achievements-weekly/**, /api/v1/achievements-step, /api/v1/achievements-step/**, /api/v1/commands/*/set-achievement/**
            - Method=POST,PATCH,DELETE
          metadata:
            auth-roles:
              - admin-diar
              - therapist-diar
        - id: achievements-manager
          uri: http://achievements-manager
          predicates:
            - Path=/api/v1/achievements/**, /api/v1/achievements-monthly/**, /api/v1/achievements-weekly/**, /api/v1/achievements-scheduled/**, /api/v1/step-user/**, /api/v1/achievements-step/**, /api/v1/achievements-step, /api/v1/achievement-user/**, /api/v1/achievements-manager/api-doc
            - Method=GET
        - id: statistics
          uri: http://statistics
          predicates:
            - Path=/api/v1/statistics/presence/**, /api/v1/statistics/api-doc
            - Method=GET
          filters:
            - AddPrincipalToPathFilter
#            API GW security impl should be corrected
#        - id: statistics-admin
#          uri: http://statistics
#          order: 1
#          predicates:
#            - Path=/api/v1/statistics/presence/**
#            - Method=GET
#          metadata:
#            auth-roles:
#              - admin-diar
#              - therapist-diar
        - id: multimedia
          uri: http://multimedia-manager
          predicates:
            - Path=/api/v1/multimedia, /api/v1/multimedia/**, /api/v1/multimedia-manager/**
        - id: data-aggregator
          uri: http://data-aggregator
          predicates:
            - Path=/api/v1/mapp/**, /api/v1/data-aggregator/api-doc
            - Method=GET
          filters:
            - AddPrincipalToPathFilter
keycloak-client:
  server-url: https://auth-dev.thehousehealth.com/auth
