spring:
  datasource:
    url: jdbc:postgresql://database-prod-2.co7q08si9fnn.eu-north-1.rds.amazonaws.com:5432/ai-management?ssl=false
    username: postgres
    password: '{cipher}d6f1d7a17d572c376745b296b6c27ed73cf56defd04a81803814817be2785cc01850c2518300838d20abe80ebeed750c'
    hikari:
      maximum-pool-size: 5
      initial-pool-size: 1
      connection-timeout: 20000
  kafka:
    bootstrap-servers: b-1.agenatech-dev.9cindp.c2.kafka.eu-north-1.amazonaws.com:9094, b-2.agenatech-dev.9cindp.c2.kafka.eu-north-1.amazonaws.com:9094