spring:
  datasource:
    url: jdbc:postgresql://database-qa-1.co7q08si9fnn.eu-north-1.rds.amazonaws.com:5432/ai-management?ssl=false
    username: postgres
    password: '{cipher}a4e03ee319ea9826cc10fcc845a80efd6eae373cf657616d6f80c1e4bc505694acc70302e230452c15b7b215c3415261'
    hikari:
      maximum-pool-size: 5
      initial-pool-size: 1
      connection-timeout: 20000
  kafka:
    bootstrap-servers: b-1.kafkaqa.238fcd.c2.kafka.eu-north-1.amazonaws.com:9094, b-2.kafkaqa.238fcd.c2.kafka.eu-north-1.amazonaws.com:9094