server:
  port: 9090
spring:
  application:
    name: ai-management
  datasource:
    url: jdbc:postgresql://localhost:5432/ai-management?ssl=false
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # use validate in production
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      name: card-reply
    consumer:
      group-id: ai-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: com.agenatech.aim.model
        spring.json.value.default.type: com.agenatech.aim.model.CardReply
  flyway:
    enabled: false
    validate-on-migrate: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: basic
logging:
  level:
    root: INFO
amazon:
  aws:
    accesskey: ${AIM_AWS_ACCESS_KEY_ID:test}
    secretkey: ${AIM_AWS_SECRET_ACCESS_KEY:test}
springdoc.api-docs.path: /api/v1/ai-management/api-doc
ai.physiology.url: http://physiology.servebeer.com/
ai.questionnaire.url: http://questionnaire.ai.diar.tech/
health:
  config:
    enabled: false