spring:
  datasource:
    url: jdbc:postgresql://agenatech.cbxabex1bwiq.eu-north-1.rds.amazonaws.com:5432/gamificaton-manager?ssl=false
    username: postgres
    password: '{cipher}d0a1612fe2e66a648757a4726cf577501f596b6f6816a7eaf055b87dc3dd030bbf263d97f3976c62f877b900af366c9e'
    hikari:
      maximum-pool-size: 5
      initial-pool-size: 1
      connection-timeout: 20000
  kafka:
    enabled: true
    bootstrap-servers: b-1.agenatech-dev.9cindp.c2.kafka.eu-north-1.amazonaws.com:9094, b-2.agenatech-dev.9cindp.c2.kafka.eu-north-1.amazonaws.com:9094
    properties:
      security.protocol: SSL
    producer:
      bootstrap-servers: b-1.agenatech-dev.9cindp.c2.kafka.eu-north-1.amazonaws.com:9094, b-2.agenatech-dev.9cindp.c2.kafka.eu-north-1.amazonaws.com:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: reply:com.agenatech.gamificationmanager.model.ExecutedCardUserRelation
    topic:
      name: card-reply
        replicas: 2
        partitions: 3
