server:
  port: 8989
spring:
  kafka:
    enabled: true
    bootstrap-servers: b-1.agenatech-dev.9cindp.c2.kafka.eu-north-1.amazonaws.com:9094, b-2.agenatech-dev.9cindp.c2.kafka.eu-north-1.amazonaws.com:9094
    properties:
      security.protocol: SSL
    producer:
      bootstrap-servers: b-1.agenatech-dev.9cindp.c2.kafka.eu-north-1.amazonaws.com:9094, b-2.agenatech-dev.9cindp.c2.kafka.eu-north-1.amazonaws.com:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: profile:com.agenatech.solutions.profiles.model.UserProfile
    topic:
      name: user-profile-create
      replicas: 2
      partitions: 3
    step.topic:
      name: step-update
      replicas: 2
      partitions: 3
    delete.topic:
      name: user-profile-delete
      replicas: 2
      partitions: 3
  datasource:
    url: jdbc:postgresql://agenatech.cbxabex1bwiq.eu-north-1.rds.amazonaws.com:5432/profiles-diar?ssl=false
    username: postgres
    password: '{cipher}d0a1612fe2e66a648757a4726cf577501f596b6f6816a7eaf055b87dc3dd030bbf263d97f3976c62f877b900af366c9e'
    hikari:
      maximum-pool-size: 5
      initial-pool-size: 1
      connection-timeout: 20000
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        cache:
          redisson:
            entity.expiration.max_idle_time: 604800000
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      cache:
        use_second_level_cache: true
        factory_class: org.redisson.hibernate.RedissonRegionFactory
        redisson:
          fallback: true
  redis:
    ssl: true
    redisson:
      config: |
        masterSlaveServersConfig:
          retryAttempts: 3
          retryInterval: 1500
          loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
          masterAddress: "redis://agenatech.yle1ni.ng.0001.eun1.cache.amazonaws.com:6379"
          slaveAddresses:
            - "redis://agenatech-002.yle1ni.0001.eun1.cache.amazonaws.com:6379"
            - "redis://agenatech-003.yle1ni.0001.eun1.cache.amazonaws.com:6379"



