server:
  port: 8989
spring:
  kafka:
    enabled: true
    bootstrap-servers: b-1.kafkaqa.238fcd.c2.kafka.eu-north-1.amazonaws.com:9094, b-2.kafkaqa.238fcd.c2.kafka.eu-north-1.amazonaws.com:9094
    properties:
      security.protocol: SSL
    producer:
      bootstrap-servers: b-1.kafkaqa.238fcd.c2.kafka.eu-north-1.amazonaws.com:9094, b-2.kafkaqa.238fcd.c2.kafka.eu-north-1.amazonaws.com:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: profile:com.agenatech.solutions.profiles.model.UserProfile
    topic:
      name: user-profile
      replicas: 2
      partitions: 3
    consumer:
      group-id: profiles
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      step-topic.name: step-update-request
      payment-topic.name: client-payments
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: step:com.agenatech.solutions.profiles.client.kafka.consumer.payload.StepUpdateDto,payment:com.agenatech.solutions.profiles.client.kafka.consumer.payload.PaymentEventDto
        bootstrap.servers: b-1.kafkadev.ew7c9m.c2.kafka.eu-north-1.amazonaws.com:9094, b-2.kafkadev.ew7c9m.c2.kafka.eu-north-1.amazonaws.com:9094
        security.protocol: SSL
        session.timeout.ms: 45000

  datasource:
    url: jdbc:postgresql://database-qa-1.co7q08si9fnn.eu-north-1.rds.amazonaws.com:5432/profiles?ssl=false
    username: postgres
    password: '{cipher}a4e03ee319ea9826cc10fcc845a80efd6eae373cf657616d6f80c1e4bc505694acc70302e230452c15b7b215c3415261'
    hikari:
      maximum-pool-size: 5
      initial-pool-size: 1
      connection-timeout: 20000
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        cache.redisson:
          entity.expiration.max_idle_time: 604800000
          config: redisson-qa.yml

    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      cache:
        use_second_level_cache: true
        factory_class: org.redisson.hibernate.RedissonRegionFactory
        redisson:
          fallback: true

  redis:
    ssl: true
    redisson:
      config: |
        masterSlaveServersConfig:
          retryAttempts: 3
          retryInterval: 1500
          loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
          masterAddress: "redis://qa-001.7rswex.0001.eun1.cache.amazonaws.com:6379"
          slaveAddresses:
            - "redis://qa-002.7rswex.0001.eun1.cache.amazonaws.com:6379"
            - "redis://qa-003.7rswex.0001.eun1.cache.amazonaws.com:6379"



notifications:
  url: http://notification-service
  email-url: /api/v1/emails/relapse