server:
  port: 8080
spring:
  kafka:
    enabled: true
    consumer:
      group-id: cards-execution-statistics
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      executed-card-topic:
        name: card-reply
        group-id: cards-execution-statistics
      profile-deleted-topic:
        name: user-profile-delete
        group-id: statistics
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: reply:com.agenatech.statistics.model.ExecutedCard,profile:com.agenatech.statistics.model.UserProfile
        bootstrap.servers: b-1.agenatech-dev.9cindp.c2.kafka.eu-north-1.amazonaws.com:9094, b-2.agenatech-dev.9cindp.c2.kafka.eu-north-1.amazonaws.com:9094
        security.protocol: SSL
        session.timeout.ms: 45000
  datasource:
    url: jdbc:postgresql://agenatech-2.cbxabex1bwiq.eu-north-1.rds.amazonaws.com:5432/statistics-manager?ssl=false
    username: postgres
    password: '{cipher}d0a1612fe2e66a648757a4726cf577501f596b6f6816a7eaf055b87dc3dd030bbf263d97f3976c62f877b900af366c9e'
    hikari:
      maximum-pool-size: 5
      initial-pool-size: 1
      connection-timeout: 20000