server:
  port: 8078
spring:
  data.rest.base-path: api/v1
  datasource:
    url: jdbc:postgresql://localhost:5432/statistics-manager?ssl=false
    username: user
    password: password
  jpa:
    properties:
      hibernate:
        generate_statistics: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  kafka:
    enabled: true
    consumer:
      group-id: cards-execution-statistics
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      executed-card-topic.name: card-reply
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: reply:com.agenatech.statistics.model.ExecutedCard
        sasl:
          mechanism: PLAIN
          jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule   required username='3S7RWXX65P6OKXSU'   password='JnOxlex27gBpIZeAd5xznmfLaojL0K2pxtPz9F1Cx+++gfYefR2JN/y+cW/5q9Wb';
        bootstrap.servers: pkc-zm3p0.eu-north-1.aws.confluent.cloud:9092
        security.protocol: SASL_SSL
        session.timeout.ms: 45000
        basic.auth.credentials.source: USER_INFO
        basic.auth.user.info: 3S7RWXX65P6OKXSU:JnOxlex27gBpIZeAd5xznmfLaojL0K2pxtPz9F1Cx+++gfYefR2JN/y+cW/5q9Wb

management.endpoints.web.exposure.include: '*'
springdoc.api-docs.path: /api/v1/statistics/api-doc
sentry:
  dsn: https://d2c258aaf0194406a4b684d5671b8f03@o1167145.ingest.sentry.io/6257927
logging:
  level:
    com.agenatech: DEBUG
health:
  config:
    enabled: false



