server:
  forward-headers-strategy: framework
spring:
  data.rest.base-path: api/v1
  datasource:
    url: jdbc:postgresql://localhost:5432/achievements-manager?ssl=false
    username: user
    password: password
  jpa:
    properties:
      hibernate:
        generate_statistics: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  kafka:
    enabled: true
    consumer:
      bootstrap-servers: 127.0.0.1:56690
      group-id: profiles-achievements
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      profiles-achievements-topic.name: user-profile-create
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: profile:com.agenatech.achievementsmanager.client.kafka.payload.UserProfile
achievements.chunk.size: 100
management:
  endpoints:
    web:
      exposure:
        include: '*'
springdoc.api-docs.path: /api/v1/achievements-manager/api-doc
sentry:
  dsn: https://d2c258aaf0194406a4b684d5671b8f03@o1167145.ingest.sentry.io/6257927
logging:
  level:
    com.agenatech: DEBUG
health:
  config:
    enabled: false



