spring:
  kafka:
    enabled: true
nets:
  checkout-url: https://client-portal-qa.thehousehealth.com/onboarding

events:
  client-payments:
    profiles-url: http://profiles/api/v1/update-payment-status