server:
  port: 8086

profiles:
  url: http://localhost:8989
  path: api/v1/profiles
gamification-manager:
  url: http://localhost:8080
  path: api/v1/aggregate/gm/home
achievements-manager:
  url: http://localhost:8182
  path: api/v1/achievement-user/list

spring:
  cache:
    type: redis
    redis:
      cache-null-values: false
      time-to-live: 40000
  redis:
    #    ssl: true
    redisson:
      config: |
        singleServerConfig:
          address: "redis://localhost:6379"

logging:
  level:
    com.house: DEBUG
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: full

springdoc.api-docs.path: /api/v1/data-aggregator/api-doc

health:
  config:
    enabled: false

sentry:
  dsn: https://d2c258aaf0194406a4b684d5671b8f03@o1167145.ingest.sentry.io/6257927

