server:
  port: 8080

profiles:
  url: http://profiles
gamification-manager:
  url: http://gamification-manager
achievements-manager:
  url: achievements-manager

spring:
  cache:
    type: redis
    redis:
      cache-null-values: false
      time-to-live: 43200000
  redis:
    ssl: true
    redisson:
      config: |
        masterSlaveServersConfig:
          retryAttempts: 3
          retryInterval: 1500
          loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
          masterAddress: "redis://agenatech.yle1ni.ng.0001.eun1.cache.amazonaws.com:6379"
          slaveAddresses:
            - "redis://agenatech-002.yle1ni.0001.eun1.cache.amazonaws.com:6379"
            - "redis://agenatech-003.yle1ni.0001.eun1.cache.amazonaws.com:6379"
